import 'package:eatfit/models/exercise.dart';

final List<Exercise> exerciseList = [
  Exercise(
    '0',
    'Ex1',
    '25',
    'audio/SDM_9.mp3',
    'assets/gifs/SDM_9.gif',
  ),
  Exercise(
    '1',
    'Ex2',
    '30',
    'audio/SDM_12.mp3',
    'assets/gifs/SDM_12.gif',
  ),
  Exercise(
    '2',
    'Ex3',
    '50',
    'audio/SDM_18.mp3',
    'assets/gifs/SDM_18.gif',
  ),
  Exercise(
    '3',
    'Ex4',
    '20',
    'audio/SDM_23.mp3',
    'assets/gifs/SDM_23.gif',
  ),
  Exercise(
    '4',
    'Ex5',
    '25',
    'audio/SDM_58.mp3',
    'assets/gifs/SDM_58.gif',
  ),
  Exercise(
    '5',
    'Ex6',
    '30',
    'audio/SDM_65.mp3',
    'assets/gifs/SDM_65.gif',
  ),
];
